version: '3'

services:
  bot:
    image: ghcr.io/discoreme/sadbot
    environment:
      - SADBOT_TOKEN: "123456:qwerty"
      - SADBOT_OPEN_WEATHER_TOKEN: "qwerty"

  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes